version: "3"

services:
  mockuni-client:
    image: mockuni-client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - mockuni-api
  mockuni-api:
    image: mockuni-api
    ports:
      - "5000:5000"
    networks:
      - mern-app
      
networks:
  mern-app:
    driver: bridge